# Permalinks
permalink:           pretty

# Setup
title:               Jon Lazar
tagline:             
url:                 http://www.jlazar.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jon Lazar
  url:               https://www.jlazar.com
  email:             jon.lazar@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/JonLz/jlazar.com

highlighter: rouge
markdown: redcarpet

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
